from collections import defaultdict
from pathlib import Path


def _group_by_path(points):
    groups = defaultdict(list)
    for p in points:
        groups[(p.layer_id, p.polygon_id)].append(p)
    return [sorted(groups[k], key=lambda p: p.point_id) for k in sorted(groups)]


def export_gcode(points, cfg):
    g = cfg['gcode']
    path = Path(g['output_path'])
    path.parent.mkdir(parents=True, exist_ok=True)

    dep_f = float(g['deposition_feedrate'])
    travel_f = float(g['travel_feedrate'])
    clearance = float(g['safe_z_clearance'])
    arc_on = str(g['arc_start_command'])
    arc_off = str(g['arc_stop_command'])
    on_dwell = int(g.get('arc_start_dwell_ms', 0))
    off_dwell = int(g.get('arc_stop_dwell_ms', 0))

    lines = ['; Generated by WAAM Slicer MVP', 'G21', 'G90', '']
    for pts in _group_by_path(points):
        if len(pts) < 2:
            continue
        first = pts[0]
        safe_z = first.z + clearance
        lines.append(f'; layer={first.layer_id} path={first.polygon_id} offset={first.offset_index}')
        lines.append(f'G0 Z{safe_z:.4f} F{travel_f:.1f}')
        lines.append(f'G0 X{first.x:.4f} Y{first.y:.4f} F{travel_f:.1f}')
        lines.append(f'G0 Z{first.z:.4f} F{travel_f:.1f}')
        lines.append(arc_on)
        if on_dwell > 0:
            lines.append(f'G4 P{on_dwell}')

        for p in pts[1:]:
            lines.append(f'G1 X{p.x:.4f} Y{p.y:.4f} Z{p.z:.4f} F{dep_f:.1f}')
            if p.status == 'ARC_STOP':
                lines.append(arc_off)
                if off_dwell > 0:
                    lines.append(f'G4 P{off_dwell}')

        lines.append(f'G0 Z{safe_z:.4f} F{travel_f:.1f}')
        lines.append('')

    lines.extend(['M2', ''])
    path.write_text('\n'.join(lines), encoding='utf-8')
    return path
